[workspace]
members = ["scores", "tests"]
resolver = "2"

[profile.dev]
opt-level = 0
lto = false
debug = true
codegen-units = 16

[profile.release]
opt-level = 3
lto = true
debug = true
codegen-units = 1
