[package]
name = "scores"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "A binary crate for calculating bowling ball scores."
authors = ["RedIsGaming <>, Dwarffish <>"]

[dependencies]
rand = "0.8.5"
